/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = { 
  apiSidebar: [
    'getting-started',
    {
      type: 'category',
      label: 'Overview',
      items: ['overview/intro', 'overview/dataconnectors', 'overview/llmtools', 'overview/faq'],
    },
    {
      type: 'category',
      label: 'API',
      items: [
        'api/yaml',
        'api/cli',
        {
          type: 'category',
          label: 'Data Connectors',
          items: ['api/connectors/firestore', 'api/connectors/email', 'api/connectors/gdrive', 
            {
              type: 'category',
              label: 'Security',
              items: [ {type: 'autogenerated',  dirName: 'api/connectors/Security'} ],
            } 
          ],
        },
        {
          type: 'category',
          label: 'LLM Tools',
          items: ['api/llmtools/train', 'api/llmtools/huggingFace', 'api/llmtools/heroku', 'api/llmtools/chatbot'],
        }
      ],
    },
    'overview/contributors'
  ], 
};

export default sidebars;
